blog/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('blogin.urls', 'blogin'), namespace="blogin")),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='blogin:login'), name='auth_logout'),
    url(r'^accounts/password/change$', auth_views.PasswordChangeView.as_view (template_name='password_change.html',success_url=reverse_lazy('blogin:login')),name='auth_password_change'),
]

blogin/urls.py
from django.conf.urls import url
from .views import index, add_post, view_post, delete_comment, update_post, login

urlpatterns = [
    url(r'^$', login, name='login'),
    url(r'^index$', index, name='index'),
    url(r'^add_post$', add_post, name='add-post'),
    url(r'^view_post/(?P<post_id>\d+)$', view_post, name='view-post'),
    url(r'^delete_comment/(?P<comment_id>\d+)$', delete_comment, name='delete-comment'),
    url(r'^update_post/(?P<post_id>\d+)$', update_post, name='update-post'),
]

blogin/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name="Title", max_length=200)
    body = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.title

    class Meta:
        ordering  = ('-create_date',)

class Comment(models.Model):
    post = models.ForeignKey(Post, verbose_name="Post", related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    body = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.name
    
    class Meta:
        ordering  = ('-create_date',)

blogin/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blogin/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import CommentForm, PostForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Comment

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        template = 'list.html'
        posts = Post.objects.all()
        context = {
            'posts': posts
        }
        return render(request, template, context)
    else:
        return HttpResponseRedirect(reverse_lazy('auth_login'))

def add_post(request):
    if request.user.is_authenticated:
        template = 'add_post.html'
        
        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                form.save()
            return redirect('blogin:index')
        else:
            context = {
                'form': PostForm()
            }
            return render(request, template, context)
    else:
        return HttpResponseRedirect(reverse_lazy('auth_login'))

def view_post(request, post_id):
    if request.user.is_authenticated:
        template = 'view_post.html'
        posts = Post.objects.get(id=int(post_id))

        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = posts
                comment.save()
                
            return redirect('blogin:view-post', post_id=post_id)
        
        else:
            form = CommentForm()

        context = {
                'posts': posts, 'form':form
            }
            
        return render(request, template, context)
    else:
        return HttpResponseRedirect(reverse_lazy('auth_login'))
    
def delete_comment(request, comment_id):
    if request.user.is_authenticated:
        comment = Comment.objects.get(id=int(comment_id))
        comment_pid = comment.post_id
        comment.delete()

        return redirect('blogin:view-post', post_id=comment_pid)
    else:
        return HttpResponseRedirect(reverse_lazy('auth_login'))

def update_post(request, post_id):
    if request.user.is_authenticated:
        template = 'update_post.html'
        post = Post.objects.get(id=int(post_id))
        
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                form.save()
            return redirect('blogin:index')
        else:
            context = {
                'form': PostForm(instance=post)
            }
            return render(request, template, context)
    else:
        return HttpResponseRedirect(reverse_lazy('auth_login'))

def login(request):
    if request.user.is_authenticated:
    	return HttpResponseRedirect(reverse_lazy('blogin:index'))
    else:
        return HttpResponseRedirect(reverse_lazy('auth_login'))

templates/add_post.html
{% extends 'base.html' %}

{% block title %} Add Post | {% endblock %}

{% block content %}
	<section class="hero">
    	<div class="hero-body">
      		<div class="container">
      			<section class="section">
      				<div class="columns">
           				 <div class="column is-8 is-offset-2">
           				 	<div class="content is-medium">
           				 		<h1> Add Post </h1>
								<form method="post" class="mb-6">
									{% csrf_token %}
									{{ form.as_p }}
									<div class="field">
										<div class="control">
											<button class="button is-success">Submit</button>
										</div>
									</div>
								</form>
           				 	</div>
              			</div>
              		</div>
              	</section>
            </div>	
        </div>
    </section>		
{% endblock %}

templates/base.html
<!DOCTYPE html>

<html>
	<head>
		<meta charset="UTF-8">
  		<meta name="viewport" content="width=device-width, initial-scale=1.0">
  		<meta http-equiv="X-UA-Compatible" content="ie=edge">

		<title>{% block title %}{% endblock %}Travel Blog</title>

		<link rel="stylesheet" href="https://unpkg.com/bulma@0.9.2/css/bulma.min.css" />

		 <style>
   			nav.navbar {
      			height: 6rem !important;
      			box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06) !important;
    		}
 		</style>
	</head>

	<body>
		  <!-- START NAV -->
		  <nav class="navbar">
		    <div class="container">
		      <div class="navbar-brand">
		        <a class="navbar-item" href="/">
		          <strong>Travel Blog</strong>
		        </a>
		        <span class="navbar-burger burger" data-target="navbarMenu">
		          <span></span>
		          <span></span>
		          <span></span>
		        </span>
		      </div>
		    </div>
		  </nav>
		  <!-- END NAV -->


		<section class="section"> 
			<div class="container"> 
				{% block content %}
				{% endblock %}
			</div>
		</section>
	</body>
</html>

templates/list.html
{% extends 'base.html' %}

{% block title %} Home | {% endblock %}

{% block content %}
	<section class="hero">
    	<div class="hero-body">
    		<div class="column is-8 is-offset-1">
    			<h1><a href="{% url 'auth_logout' %}">Logout</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'auth_password_change' %}">Change Password</a></h1><br/><br/><a href="{% url 'blogin:add-post' %}">Add Post</a></h1>
    		</div>
      		<div class="container">
      			<section class="section">
      				<div class="columns">
           				 <div class="column is-8 is-offset-2">
           				 	{% for post in posts %}
	           				 	<div class="content is-medium">
	               					<h2 class="subtitle is-4">{{ post.create_date|date:"D d M Y" }}</h2>
	                				<h1 class="title">{{ post.title }}</h1>
	                				<div class="content is-small column is-8 is-offset-2">
	                					<p style="text-indent: 40px"><a href="{% url 'blogin:view-post' post.id %} ">View</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'blogin:update-post' post.id %}">Update</a></p>
	                				</div>
	                				<br/> 
	              				</div>
	              			{% empty %}
	              				<p>No blog posts yet</p>
              				{% endfor %}
              			</div>
              		</div>
              	</section>
            </div>	
        </div>
    </section>		
{% endblock %}

templates/login.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        <style type="text/css">
            html,
            body {
                height: 100%;
            }

            body {
                padding-top: 40px;
                padding-bottom: 40px;
            }

            .form-signin {
                width: 100%;
                max-width: 330px;
                padding: 15px;
                margin: auto;
            }
        </style>

    </head>

    <body class="text-center">
        <form class="form-signin" method="POST" action="{% url 'auth_login' %}" role="form">
            {% csrf_token %}

            <h1>Travel Blog</h1>

            {{ form.username.label }}
            {{ form.username }}

            {{ form.password.label }}
            {{ form.password }}

            <button class="btn btn-lg btn-primary" type="submit">Sign in</button>
            <input type="hidden" name="next" value="{% url 'blogin:index' %}" />
        </form>
    </body>
</html>

templates/password_change.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>Travel Blog</h1>
		<a href="{% url 'auth_logout' %}">Logout</a> <br /><br />

		{{ form.errors }}

		<form method="POST" action="{% url 'auth_password_change' %}">
		    {% csrf_token %}

		    {{ form.old_password.label }}
		    {{ form.old_password }} <br /><br />

		    {{ form.new_password1.label }}
		    {{ form.new_password1 }} <br /><br />
		    
		    {{ form.new_password2.label }}
		    {{ form.new_password2 }} <br /><br />

		    <button type="submit" class="btn btn-success">Change password</button>
		</form>
	</body>
</html>

templates/update_post.html
{% extends 'base.html' %}

{% block title %} Add Post | {% endblock %}

{% block content %}
	<section class="hero">
    	<div class="hero-body">
      		<div class="container">
      			<section class="section">
      				<div class="columns">
           				 <div class="column is-8 is-offset-2">
           				 	<div class="content is-medium">
           				 		<h1> Update Post </h1>
								<form method="post" class="mb-6">
									{% csrf_token %}
									{{ form.as_p }}
									<div class="field">
										<div class="control">
											<button class="button is-success">Submit</button>
										</div>
									</div>
								</form>
           				 	</div>
              			</div>
              		</div>
              	</section>
            </div>	
        </div>
    </section>		
{% endblock %}

templates/view_post.html
{% extends 'base.html' %}

{% block title %} {{post.title}} | {% endblock %}

{% block content %}
	<section class="hero">
    	<div class="hero-body">
      		<div class="container">
      			<section class="section">
      				<div class="columns">
           				 <div class="column is-8 is-offset-2">
           				 	<div class="content is-medium">
           				 		<h2 class="subtitle is-4">{{ posts.create_date|date:"D d M Y" }}</h2>
           				 		<h1 class="title">{{ posts.title }}</h1>
           				 		<br/> 
           				 		{% if post.image %}
	           				 		<figure class="image">
	           				 			<img src="{{ posts.image.url }}">
	           				 		</figure>	
	           				 		{% endif %}
           				 		<p>{{ posts.body }}</p>

           				 		<hr>

           				 		<h2 class="subtitle is-4">Comments</h2>

								<form method="post" class="mb-6">
									{% csrf_token %}
									{{ form.as_p }}

									<div class="field">
										<div class="control">
											<button class="button is-success">Submit comment</button>
										</div>
									</div>
								</form>

								{% for comment in posts.comments.all %}
									<article class="media box">
										<div class="media-content">
											<strong>{{ comment.name }}</strong> <small>{{ comment.create_date|timesince }} ago</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'blogin:delete-comment' comment.id %}" class="btn btn-danger">Delete</a><br>
											{{ comment.body }}
										</div>
									</article>
								{% endfor %}
           				 	</div>
              			</div>
              		</div>
              	</section>
            </div>	
        </div>
    </section>		
{% endblock %}